/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args){
        Mobile mobile = new Mobile("N95", "Red", "Nokia");
        iPhone iPhone = new iPhone("iPhone XS", "White", "Apple");
        Android android = new Android("XZ Premium", "Black", "Sony");
        Person person = new Person("Antonio", mobile);
        Person antony = new Person("Antony", mobile);
        IPhoneRobot iPhoneRobot = new IPhoneRobot("Robot", iPhone);

        person.makeCall("Antonio make a call but no one cares.");

        antony.makeCall("Hey there, I am Antony. And I am using Nokia N95.");
        antony.setMobile(android);
        antony.makeCall("Sony is better than Apple la!!");
        antony.makeCall("Sony is better than Apple la of coz!!");

        iPhoneRobot.makeCall("I am using iPhone XS now");
        iPhoneRobot.makeCall("I want to buy an iPhone XS Max...");

    }
}
